### ISSUE TITLE
Introduce vimeo pageitem

### ISSUE THREAD

**Issue by b-g** [DigitalDesignIO/dmd-documenation-generator#2]
E.g. `3.vimeo` file with the following content:

``` json
{
"id": 157991947,
"width": 1920,
"height": 1080
}
```

**Comment by b-g** [comment]
Please document the vimeo feature here too
https://github.com/DigitalDesignIO/dmd-documenation-generator#supported-media

**Comment by Andi-Lo** [comment]
added vimeo feature to documentation in commit 0b25cff
