### ISSUE TITLE
Different grid size between generator and dmd website

### ISSUE THREAD

**Issue by Andi-Lo** [DigitalDesignIO/dmd-documenation-generator#7]
I noticed we got different grid sizes in the generator and the website. This yields us to the problem, that the content of the generator can not be transferred to the website without doing lots of optimizing and handwork.

Here is my suggestion for a solution:
- we should change the grid size in the generator and in the DMD project sites to match one common layout
- I will change the image and p5js content of the 2 documentations you provided me to get a homogeneous layout that looks nice and clean.

---
- The next students who use the generators should optimize their pictures for the new grid size
- Because the grid size changes then the canvas size of the P5.js content also has to be adjusted

Edit: I Have to rethink about how we adjust the grid, maybe it is better if I will adjust the DMD project layout and we keep the generator grid like it is now. I have to investigate it further before I can see the best solution for this.

Thoughts @b-g ?

**Comment by b-g** [comment]
Odd. Both should be the same. I believe that derived my grid from the original layout by Marco. The very wide one e.g. https://digitalmediadesign.io/projects/the-villa of ~740px width is IMO the weaker one (text lines go too long if you look on it with strict typography rules in mind). Rather keep the one of the docu gen.

**Comment by Andi-Lo** [comment]
I adjusted the project grid size on the website
Fixed by commit: https://github.com/DigitalDesignIO/dmd-website/commit/c49e678f3491189a615e74b9ab48978a21759b6e
