### ISSUE TITLE
Preventing p5js.min from printing to dev console?

### ISSUE THREAD

**Issue by Andi-Lo** [DigitalDesignIO/dmd-documenation-generator#8]
@b-g do you know a way of preventing the p5js lib to print to the developer console?

Currently it is really spamming it and for me the viewport starts to lag on some p5js iframes.

![p5bug](https://cloud.githubusercontent.com/assets/7545568/16154155/e5f6d906-34a9-11e6-8e8b-e47eacbb44a1.gif)

**Comment by b-g** [comment]
Yes, not so great! I would recommend to add a function like removeLogging()

```
userScript.text = "new p5();\n" + _removeLogging(this.props.content);
```

https://github.com/DigitalDesignIO/dmd-documenation-generator/blob/master/src/components/PageItemP5.react.js#L38

In removeLogging() I would parse every line of the p5js sketch file:
1. trim whitespace
2. if the line starts with print or console ... remove it
return remaining joined lines of p5js sketch file as a single string
